name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Create .env file
        run: |
          echo "SERVER_URL=${{ secrets.GITHUB_TOKEN.SERVER_URL }}" >> .env
          echo "JWT_SECRET_KEY=${{ secrets.GITHUB_TOKEN.JWT_SECRET_KEY }}" >> .env
          echo "ENCRYPTION_SECRET=${{ secrets.GITHUB_TOKEN.ENCRYPTION_SECRET }}" >> .env

      - name: Run tests
        run: |
          pytest

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.json
